/**
 * Regenerates agent/lib/pricing.ts from the live Token Factory catalog.
 *
 *   node --env-file=.env.local --import ./scripts/ts-resolve.mjs scripts/refresh-pricing.ts
 *
 * Token Factory reports no per-call cost, so cost has to be computed from
 * token counts. GET /v1/models?verbose=true carries `pricing.prompt` and
 * `pricing.completion` as dollars *per token*; we store dollars per million.
 */
import { writeFileSync } from "node:fs";
import { TOKEN_FACTORY_BASE_URL } from "../agent/lib/nebius.ts";

const key = process.env.NEBIUS_API_KEY?.trim();
if (!key) throw new Error("NEBIUS_API_KEY is required");

const res = await fetch(`${TOKEN_FACTORY_BASE_URL}/models?verbose=true`, {
  headers: { authorization: `Bearer ${key}` },
});
if (!res.ok) throw new Error(`catalog ${res.status}`);
const body = (await res.json()) as {
  data: Array<{ id: string; context_length?: number; pricing?: { prompt?: string; completion?: string } }>;
};

const rows = body.data
  .filter((m) => m.pricing?.prompt)
  .sort((a, b) => a.id.localeCompare(b.id))
  .map((m) => {
    const round = (n: number) => Math.round(n * 1e4) / 1e4;
    const inM = round(Number(m.pricing?.prompt ?? 0) * 1e6);
    const outM = round(Number(m.pricing?.completion ?? 0) * 1e6);
    return `  "${m.id}": { in: ${inM}, out: ${outM}, context: ${m.context_length ?? 0} },`;
  });

const file = `// Generated by scripts/refresh-pricing.ts on ${new Date().toISOString().slice(0, 10)}.
// Dollars per MILLION tokens, from GET /v1/models?verbose=true.
export const TOKEN_FACTORY_PRICING: Record<string, { in: number; out: number; context: number }> = {
${rows.join("\n")}
};
`;
writeFileSync(new URL("../agent/lib/pricing.generated.ts", import.meta.url), file);
console.log(`wrote ${rows.length} models`);
